version: '3.7'

services:

  apache-and-php-server-BIQ:
    container_name: BIQ
    tty: true
    stdin_open: true
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile
    image: olisteves/biq:latest
    ports:
      - 8090:80
      - 8043:443
    volumes:
      - ./app:/var/www/html
    networks:
      - webapp_network

# Custom network for composed containers to communicate on
networks:
  webapp_network:
    driver: bridge
